name: dns_client
description: Dart implementation of DNS-over-HTTPS.
version: 0.2.1
homepage: https://github.com/dietfriends/dns_client

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  http: ^0.13.1
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.6.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.5
  freezed: ^1.0.0
