name: dns_client
description: Dart implementation of DNS-over-HTTPS client.
version: 1.0.0
homepage: https://github.com/dietfriends/dns_client

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  http: ^1.6.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.28.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
  freezed: ^3.2.4
