name: dns_client
description: Dart DNS-over-HTTPS (DoH) client supporting Google, Cloudflare, AdGuard, and Quad9 providers.
version: 1.3.1
homepage: https://github.com/dietfriends/dns_client

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  http: ^1.2.0
  http2: ^2.3.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.0
  freezed: ^3.0.0
